# -*- coding: utf-8 -*-
"""MLH LHD Visualisation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZjpZAwrc_RHNr4GRZT_weIJru71g9Usp
"""

# Commented out IPython magic to ensure Python compatibility.
try:
#     %tensorflow_version 2.x
except Exception:
  pass

"""secret handshake"""

from __future__ import absolute_import, division, print_function, unicode_literals
import pandas as pd
import seaborn as sb
import tensorflow as tf
from tensorflow import keras
from tensorflow.estimator import LinearClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score

col_names = ['SepalLength','SepalWidth','PetalLength','PetalWidth','Species']
target_dimensions = ['Setosa','Versicolor','Virginica']
training_data_path=tf.keras.utils.get_file("iris_training.csv", "https://storage.googleapis.com/download.tensorflow.org/data/iris_training.csv")
test_data_path=tf.keras.utils.get_file("iris_test.csv","https://storage.googleapis.com/download.tensorflow.org/data/iris_test.csv")

training=pd.read_csv(training_data_path,names=col_names,header=0)
training=training[training['Species']>=1]
training['Species']=training['Species'].replace([1,2],[0,1])

test=pd.read_csv(test_data_path, names=col_names,header=0)
test=test[test['Species']>=1]
test['Species']=test['Species'].replace([1,2],[0,1])

training.reset_index(drop=True, inplace=True)
test.reset_index(drop=True, inplace=True)

iris_dataset=pd.concat([training, test],axis=0)

iris_dataset.describe()

"""seaborn: huge static data
bokeh: live data
matplotlib: underlying libraries
"""

sb.pairplot(iris_dataset, diag_kind='kde')

correlation_data=iris_dataset.corr()
correlation_data.style.background_gradient(cmap='coolwarm', axis=None)

stats=iris_dataset.describe()
iris_stats=stats.transpose()
iris_stats